# Casos confirmados em cada concelho de Portugal por data

In [5]:
import psycopg2
import pandas as pd
import sqlalchemy
import matplotlib as plt

In [6]:
from sqlalchemy import create_engine

# Postgres username, password, and database name
POSTGRES_ADDRESS = 'localhost' 
POSTGRES_USERNAME = 'postgres' 
POSTGRES_PASSWORD = 'natureza123' 
POSTGRES_DBNAME = 'miebiom'
# A long string that contains the necessary Postgres login information
postgres_str = ('postgresql://{username}:{password}@{ipaddress}/{dbname}'.format(username=POSTGRES_USERNAME, password=POSTGRES_PASSWORD, ipaddress=POSTGRES_ADDRESS, dbname=POSTGRES_DBNAME))
print (postgres_str)

# Create the connection
cnx = create_engine(postgres_str)

postgresql://postgres:natureza123@localhost/miebiom

In [8]:
query = pd.read_sql_query('''SELECT * FROM covid_concelhos_portugal;''', cnx)
pd.read_sql_query('''SELECT * FROM covid_concelhos_portugal;''', cnx)

,id,data,ABRANTES,AGUIAR DA BEIRA,ALANDROAL,ALBERGARIA-A-VELHA,ALBUFEIRA,ALCANENA,ALCOBAÇA,ALCOCHETE,...,VILA VIÇOSA,VIMIOSO,VINHAIS,VISEU,VIZELA,VOUZELA,ÁGUEDA,ÉVORA,ÍLHAVO,ÓBIDOS
0,1,24/03/2020,,,,5.0,5.0,,,3.0,...,,,,6.0,,,3.0,4.0,,
1,2,25/03/2020,,,,5.0,8.0,,,3.0,...,,,,11.0,,,3.0,5.0,,
2,3,26/03/2020,,,,21.0,18.0,,,3.0,...,,,,20.0,,,10.0,8.0,10.0,
3,4,27/03/2020,,,,28.0,22.0,,,3.0,...,,,,21.0,3.0,,10.0,8.0,12.0,
4,5,28/03/2020,,,,28.0,22.0,,,3.0,...,,,,21.0,4.0,,13.0,12.0,12.0,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,59,21/05/2020,9.0,,,87.0,75.0,8.0,39.0,23.0,...,,10.0,30.0,99.0,128.0,8.0,64.0,23.0,128.0,
59,60,22/05/2020,9.0,,,87.0,75.0,8.0,39.0,23.0,...,,10.0,30.0,99.0,131.0,8.0,64.0,24.0,128.0,
60,61,23/05/2020,9.0,,,87.0,75.0,8.0,39.0,23.0,...,,11.0,30.0,99.0,131.0,8.0,64.0,25.0,128.0,
61,62,24/05/2020,10.0,,,87.0,75.0,8.0,39.0,23.0,...,,11.0,30.0,99.0,135.0,8.0,64.0,25.0,128.0,
62,63,25/05/2020,10.0,,,88.0,75.0,8.0,39.0,23.0,...,,11.0,30.0,100.0,135.0,8.0,65.0,26.0,129.0,